try {  // ReferenceError  console.log(myUndefinedProperty);} catch (e) {  // Ausgabe des Fehlers  console.log(e);} finally {  // dieser Block wird immer ausgef√ºhrt  console.log('cleanup');}